### ISSUE TITLE
gpk_admin website keep blinking after run "npm run dev"

### ISSUE THREAD

**Issue by Helenbj** [GeekPark/gpk_admin#27]
I run all commands listed in website "https://github.com/GeekPark/gpk_admin/blob/master/BACKEND.md" successfully, the output of "bundle exec rails s -p 5000" is:
```
helen@helen-Lenovo-Product:~/Documents/fbcodex/geekpark$ bundle exec rails s -p 5000
=> Booting Puma
=> Rails 5.0.2 application starting in development on http://localhost:5000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.1-p112), codename: Sassy Salamander
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:5000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2018-04-02 13:44:09 +0800
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by Rails::WelcomeController#index as HTML
  Parameters: {"internal"=>true}
  Rendering vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/templates/rails/welcome/index.html.erb
  Rendered vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/templates/rails/welcome/index.html.erb (3.3ms)
Completed 200 OK in 15ms (Views: 7.4ms | ActiveRecord: 0.0ms)

```

when I visit "http://localhost:5000/" in browser, I can see the rails runs ok:
![image](https://user-images.githubusercontent.com/33087063/38186004-5714cb20-3683-11e8-843b-8c2be4c0ab62.png)

However when I run "npm run dev" in the gpk_admin directory, the automatically open website keep blinking, the browser reports cannot get **access_key**, and the url is "http://localhost:8080/login/?callback_url=http://localhost:8080/login/?callback_url=http"

As you can see, the callback_url is the current url, which may result the website keep refreshing the current page, the source codes relate to this problem is "gpk_admin/src/components/Vheader.vue", details is in line 39 and line 55:
location.href = `${config.account}/login/?calback_url=${location.href}`
![image](https://user-images.githubusercontent.com/33087063/38186192-40dc5d54-3684-11e8-8225-1de6d559aef1.png)

I notice you have close issue like this in 2017, while I run back-end program as you answer successfully, but the blink problem is still there:
![image](https://user-images.githubusercontent.com/33087063/38186258-92bd0768-3684-11e8-86e9-3a5c2b5946f6.png)
The output of command "npm run dev" is:
```
helen@helen-Lenovo-Product:~/Documents/gpk_admin$ npm run dev

> GEEKPARK@1.0.0 dev /home/helen/Documents/gpk_admin
> node build/dev-server.js


┌─────────────────────────────────────────────────────────┐
│                 npm update check failed                 │
│           Try running with sudo or get access           │
│          to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/helen/.config │
└─────────────────────────────────────────────────────────┘
> Starting dev server...


 DONE  Compiled successfully in 6434ms                                                                                                                                                              14:51:29

> Listening at http://localhost:8080

```
and the gpk_admin website is:
![image](https://user-images.githubusercontent.com/33087063/38186405-7a0a9176-3685-11e8-9188-bce3e60262e8.png)

Hope you can help me, looking for your reply and thank you very much. @dofy @shouya @flypiggy @chen7897499 @singt7

**Comment by playmyswift** [comment]
delete this line *src/components/Vheader.vue*  37-56
``` js
  mounted () {
    // api.account.get('my/access_key').then(result => {
    //   if (Object.keys(result.data) <= 0) {
    //     location.href = `${config.account}/login/?callback_url=${location.href}`
    //     return
    //   }
    //   const url = `admin/info?access_key=${result.data.access_key}`
    //   api.get(url).then(result => {
    //     if (result.data != null) {
    //       this.info = result.data
    //       window.localStorage.setItem('username', this.info.nickname)
    //       window.localStorage.setItem('userinfo', JSON.stringify(this.info))
    //       if (result.data.roles.includes('admin') === false) {
    //         location.href = config.main
    //       }
    //     }
    //   })
    // }).catch(e => {
    //   console.log(e)
    //   location.href = `${config.account}/login/?callback_url=${location.href}`
    // })
  }
```
then refresh http://127.0.0.1:8080

**Comment by Helenbj** [comment]
I know comment these lines can make it not blink, but functions of the website are wrong, such as I cannot create any category showed in bellow picture, the browser debug output is "POST http://localhost:8080/api/v1/admin/columns?roles=dev 404 (Not Found)".
![image](https://user-images.githubusercontent.com/33087063/38188019-94ba1aa8-368c-11e8-815c-272b67644b63.png)

Does front-end gpk-admin project connect to the back-end geekpark project? Is there anything else I should do except "redis-server" + "bundle exec rails s -p 5000" + "npm run dev", or should I change the source code? 

Looking forward to your reply. @ericjjj

**Comment by playmyswift** [comment]
`vim src/config.js`

``` js
const isDev = process.env.NODE_ENV === 'development'
// 分别是
// api url
// 账号站 url
// 主站 url

const config = {
  development: {
    api: 'http://127.0.0.1:5000',
    account: '',
    main: '',
    ws: ''
  },
  production: {
    api: '',
    account: '',
    main: '',
    ws: ''
  }
}

export default isDev ? config['development'] : config['production']


```

**Comment by Helenbj** [comment]
@ericjjj Your answer finally solve this, the website now not blinks and works well, thank you very much!

**Comment by playmyswift** [comment]
and `vim geekpark/config/application.rb` , allow  cors， if you don't do that, maybe it still request error

``` ruby
require_relative 'boot'

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Geekpark
  class Application < Rails::Application
    config.generators do |g|
      g.assets false
      g.helper false
    end

    config.middleware.use Rack::Attack

    config.active_job.queue_adapter = :sidekiq
    config.middleware.insert_before 0, 'Rack::Cors' do
      allow do
        origins %r{\Ahttps?:\/\/(.*\.)?geekpark\.net\z}
        resource '/api/*', headers: :any, methods: [:get, :post, :options]
        origins '*'
        resource '/api/*',
                headers: :any,
                methods: [:get, :post, :options],
                credentials: true
        resource '/admin/*',
                headers: :any,
                methods: [:get, :post, :patch, :options, :put],
                credentials: true
        resource %r{/my/(access_key)},
                headers: :any,
                methods: [:get, :post, :patch, :options],
                credentials: true
      end
    end
  end
end

```

**Comment by playmyswift** [comment]
success:
![20180402152265664176517.png](https://ollvy8mnq.qnssl.com/20180402152265664176517.png)

**Comment by Helenbj** [comment]
Yes, I have added these configurations to geekpark/config/application.rb before, and now I can see the website locally too. You are so nice and patient to give me help, thanks much.

**Comment by Helenbj** [comment]
@ericjjj Sorry to bother you again, after checking functions of the website, I want to ask is there still many bugs here? Such as:

**1. cannot delete**
article
![image](https://user-images.githubusercontent.com/33087063/38192589-22fe9dda-36a0-11e8-99e3-1eb0778cdfe2.png)
 category
![image](https://user-images.githubusercontent.com/33087063/38192484-b197ead4-369f-11e8-9338-e11b6d5e6d47.png)
As you can see, browser output is "
**columns:1 XMLHttpRequest cannot load http://127.0.0.1:5000/api/v1/admin/columns/154?roles=dev. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.**", so if I should configure the request header from the front-end gpk-admin project?

**2. cannot create** 
article
![image](https://user-images.githubusercontent.com/33087063/38192886-c9d766ea-36a1-11e8-8b58-96be8e409e6c.png)
news
![image](https://user-images.githubusercontent.com/33087063/38193065-a56bdc4a-36a2-11e8-921c-60338aba16c4.png)
ask&answer
![image](https://user-images.githubusercontent.com/33087063/38193093-c2df9c4e-36a2-11e8-9969-e19e7d776858.png)
category (can create succssfully and see in the category list)
![image](https://user-images.githubusercontent.com/33087063/38193109-e1b67728-36a2-11e8-8dab-171eea5c24ed.png)
special-report (can create succssfully but cannot see in the special-report list)
Others also has this problem.

**3. cannot link title to content via clicking**
if clicking title in article-list or category-list, you will arrive at the page shows:
来错地方了吧🐶

Looking forward to your reply, best regards. @ericjjj

**Comment by playmyswift** [comment]
because  data structure has change,  the backend projects has not open source, this project has always been open source 😂
```
https://github.com/GeekPark/geekpark
Latest commit a5b5fde  on 23 May 2017
```

**Comment by playmyswift** [comment]
this version to correspond on *geekpark* project https://github.com/GeekPark/gpk_admin/tree/17460b7e7f4483903755d83e1196dfda80269fc1

**Comment by Helenbj** [comment]
@ericjjj The corresponding version of gpk_admin is far before, I see you have changed much till now, after I reset to previous version and run "npm run dev", the terminal output:
```
helen@helen-Lenovo-Product:~/Documents/gpk_admin$ npm run dev

> GEEKPARK@1.0.0 dev /home/helen/Documents/gpk_admin
> node build/dev-server.js


┌─────────────────────────────────────────────────────────┐
│                 npm update check failed                 │
│           Try running with sudo or get access           │
│          to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/helen/.config │
└─────────────────────────────────────────────────────────┘
Listening at http://127.0.0.1:8080

webpack: wait until bundle finished: /index.html
webpack built 0c9c583ee061bbf386cf in 6335ms
Hash: 0c9c583ee061bbf386cf
Version: webpack 1.15.0
Time: 6335ms
                            Asset     Size  Chunks       Chunk Names
 static/fonts/icomoon.0a74426.eot  15.6 kB               
 static/fonts/icomoon.9f5fd7b.ttf  15.5 kB               
static/fonts/icomoon.7d4ac7d.woff  15.6 kB               
   static/img/icomoon.f558046.svg  47.3 kB               
                           app.js  10.3 MB       0       app

ERROR in ./~/vue-echarts-v3/dist/vue-echarts.js
Module not found: Error: Cannot resolve module 'echarts' in /home/helen/Documents/gpk_admin/node_modules/vue-echarts-v3/dist
 @ ./~/vue-echarts-v3/dist/vue-echarts.js 1:85-103
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.47 MB       0       
webpack: Failed to compile.

```

In the latest version you have delete echarts from package.json, can you tell me where should I change the source code to truly run this without changing change data schema same to the back-end?
